export const data = [
  { label: "Australian Dollar", value: "AUD", flag: "🇦🇺" },
  { label: "Bulgarian Lev", value: "BGN", flag: "🇧🇬" },
  { label: "Brazilian Real", value: "BRL", flag: "🇧🇷" },
  { label: "Canadian Dollar", value: "CAD", flag: "🇨🇦" },
  { label: "Swiss Franc", value: "CHF", flag: "🇨🇭" },
  { label: "Chinese Yuan", value: "CNY", flag: "🇨🇳" },
  { label: "Czech Koruna", value: "CZK", flag: "🇨🇿" },
  { label: "Danish Krone", value: "DKK", flag: "🇩🇰" },
  { label: "Euro", value: "EUR", flag: "🇪🇺" },
  { label: "British Pound", value: "GBP", flag: "🇬🇧" },
  { label: "Hong Kong Dollar", value: "HKD", flag: "🇭🇰" },
  { label: "Hungarian Forint", value: "HUF", flag: "🇭🇺" },
  { label: "Indonesian Rupiah", value: "IDR", flag: "🇮🇩" },
  { label: "Israeli New Shekel", value: "ILS", flag: "🇮🇱" },
  { label: "Indian Rupee", value: "INR", flag: "🇮🇳" },
  { label: "Icelandic Króna", value: "ISK", flag: "🇮🇸" },
  { label: "Japanese Yen", value: "JPY", flag: "🇯🇵" },
  { label: "South Korean Won", value: "KRW", flag: "🇰🇷" },
  { label: "Mexican Peso", value: "MXN", flag: "🇲🇽" },
  { label: "Malaysian Ringgit", value: "MYR", flag: "🇲🇾" },
  { label: "Norwegian Krone", value: "NOK", flag: "🇳🇴" },
  { label: "New Zealand Dollar", value: "NZD", flag: "🇳🇿" },
  { label: "Philippine Peso", value: "PHP", flag: "🇵🇭" },
  { label: "Polish Złoty", value: "PLN", flag: "🇵🇱" },
  { label: "Romanian Leu", value: "RON", flag: "🇷🇴" },
  { label: "Swedish Krona", value: "SEK", flag: "🇸🇪" },
  { label: "Singapore Dollar", value: "SGD", flag: "🇸🇬" },
  { label: "Thai Baht", value: "THB", flag: "🇹🇭" },
  { label: "Turkish Lira", value: "TRY", flag: "🇹🇷" },
  { label: "US Dollar", value: "USD", flag: "🇺🇸" },
  { label: "South African Rand", value: "ZAR", flag: "🇿🇦" },
].map((item) => ({
  ...item,
  display: `${item.flag} ${item.value}`, // Skapar t.ex. "🇦🇺 AUD"
}));
